// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gadget-x-themes/BoldUrbanStore.tsx": () => import("../components/mockups/gadget-x-themes/BoldUrbanStore.tsx"),
  "./components/mockups/gadget-x-themes/BrightFriendlyWalkIn.tsx": () => import("../components/mockups/gadget-x-themes/BrightFriendlyWalkIn.tsx"),
  "./components/mockups/gadget-x-themes/ElectricTech.tsx": () => import("../components/mockups/gadget-x-themes/ElectricTech.tsx"),
  "./components/mockups/gadget-x-themes/HeritageWorkshop.tsx": () => import("../components/mockups/gadget-x-themes/HeritageWorkshop.tsx")
};
