// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gadget-x-themes/BoldUrbanStore.tsx": () => import("../components/mockups/gadget-x-themes/BoldUrbanStore.tsx"),
  "./components/mockups/gadget-x-themes/BrightFriendlyWalkIn.tsx": () => import("../components/mockups/gadget-x-themes/BrightFriendlyWalkIn.tsx"),
  "./components/mockups/gadget-x-themes/EditorialMagazine.tsx": () => import("../components/mockups/gadget-x-themes/EditorialMagazine.tsx"),
  "./components/mockups/gadget-x-themes/ElectricTech.tsx": () => import("../components/mockups/gadget-x-themes/ElectricTech.tsx"),
  "./components/mockups/gadget-x-themes/GarageShowroom.tsx": () => import("../components/mockups/gadget-x-themes/GarageShowroom.tsx"),
  "./components/mockups/gadget-x-themes/HeritageAtelier.tsx": () => import("../components/mockups/gadget-x-themes/HeritageAtelier.tsx"),
  "./components/mockups/gadget-x-themes/HeritageEditorial.tsx": () => import("../components/mockups/gadget-x-themes/HeritageEditorial.tsx"),
  "./components/mockups/gadget-x-themes/HeritageWorkshop.tsx": () => import("../components/mockups/gadget-x-themes/HeritageWorkshop.tsx"),
  "./components/mockups/gadget-x-themes/LocalStorefront.tsx": () => import("../components/mockups/gadget-x-themes/LocalStorefront.tsx"),
  "./components/mockups/gadget-x-themes/PlayfulRetro.tsx": () => import("../components/mockups/gadget-x-themes/PlayfulRetro.tsx"),
  "./components/mockups/gadget-x-themes/PosterStudio.tsx": () => import("../components/mockups/gadget-x-themes/PosterStudio.tsx"),
  "./components/mockups/gadget-x-themes/QuietConfident.tsx": () => import("../components/mockups/gadget-x-themes/QuietConfident.tsx"),
  "./components/mockups/gadget-x-themes/QuoteWizard.tsx": () => import("../components/mockups/gadget-x-themes/QuoteWizard.tsx"),
  "./components/mockups/gadget-x-themes/ScrollStory.tsx": () => import("../components/mockups/gadget-x-themes/ScrollStory.tsx"),
  "./components/mockups/gadget-x-themes/ServiceCatalog.tsx": () => import("../components/mockups/gadget-x-themes/ServiceCatalog.tsx")
};
