// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/okcellular-home/CatalogStorefront.tsx": () => import("../components/mockups/okcellular-home/CatalogStorefront.tsx"),
  "./components/mockups/okcellular-home/HeritageEditorial.tsx": () => import("../components/mockups/okcellular-home/HeritageEditorial.tsx"),
  "./components/mockups/okcellular-home/InstantQuote.tsx": () => import("../components/mockups/okcellular-home/InstantQuote.tsx"),
  "./components/mockups/okcellular-home/RepairConcierge.tsx": () => import("../components/mockups/okcellular-home/RepairConcierge.tsx")
};
